---
- name: Set up Docker on host
  hosts: all
  become: true
  roles:
    - docker.ubuntu
  tasks:
    - name: Install Compose Module
      pip: name=docker-compose
    - name: Upload docker-compose files
      synchronize: 
        src: ../.env
        dest: "{{ compose_dir }}/{{ project_name }}_env"

 

- include: deploy.yml
