#!/usr/bin/env ruby

registry = "registry.gitlab.com/notch8/search-frontend"

unless ARGV && ['deploy', 'provision', 'release'].include?(ARGV[0])
  raise 'please specify deploy, provision or release'
end

environment = if ARGV[1]
                " -l #{ARGV[1]}"
              else
                raise 'please specify either staging or production'
              end




if ARGV[0] == 'release'
  Dir.chdir(File.expand_path(File.dirname(__FILE__) + "/.."))
  puts Dir.pwd
  command = <<-CODE
    docker tag #{registry} #{registry}:#{ARGV[1]}-#{Time.now.strftime("%Y%m%d%I%M%S")} && \
    docker push #{registry}:#{ARGV[1]}-#{Time.now.strftime("%Y%m%d%I%M%S")} && \
    docker tag #{registry} #{registry}:#{ARGV[1]}-latest && \
    docker push #{registry}:#{ARGV[1]}-latest
    CODE
else
  Dir.chdir(File.expand_path(File.dirname(__FILE__)))
  command = "ansible-playbook -i hosts #{environment} #{ARGV[0]}.yml"
end
puts command
exec command
