image: ruby:2.3

stages:
  - build
  - test

before_script:
  - bundle

# pages:
#   stage: build
#   script:
#   - bundle exec yardoc --plugin yard-thor -o public - templates/.* templates/* 
#   artifacts:
#     paths:
#     - public
#   only:
#   - master 

test:
  script:
    - bundle exec rspec
    
