FROM phusion/passenger-ruby23:0.9.20

RUN apt-get update -qq && apt-get install -y build-essential nodejs npm pv libsasl2-dev <%= @db_libs %> && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

<% if options[:fcrepo] %>
RUN mkdir -p /opt/fits && \
    curl -fSL -o /opt/fits-0.8.5.zip http://projects.iq.harvard.edu/files/fits/files/fits-0.8.5.zip && \
    cd /opt && \
    unzip fits-0.8.5.zip && \
    chmod +x fits-0.8.5/fits.sh

<% end -%>

RUN rm /etc/nginx/sites-enabled/default
COPY ops/webapp.conf /etc/nginx/sites-enabled/webapp.conf
COPY ops/env.conf /etc/nginx/main.d/env.conf

ENV APP_HOME /home/app/webapp
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=2

ADD Gemfile* $APP_HOME/
RUN bundle check || bundle install

<% if options[:delayed_job] %>
RUN touch /var/log/worker.log && chmod 666 /var/log/worker.log
RUN mkdir /etc/service/worker
ADD ops/worker.sh /etc/service/worker/run
<% end %>

COPY . $APP_HOME
RUN chown -R app $APP_HOME

RUN rm -f /etc/service/nginx/down

CMD ["/sbin/my_init"]
