FROM ruby:2.3.0

RUN apt-get update -qq && apt-get install -y build-essential nodejs pv libsasl2-dev <%= @db_libs %> && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

<% if options[:fcrepo] %>
RUN mkdir -p /opt/fits && \
    curl -fSL -o /opt/fits-0.8.5.zip http://projects.iq.harvard.edu/files/fits/files/fits-0.8.5.zip && \
    cd /opt && \
    unzip fits-0.8.5.zip && \
    chmod +x fits-0.8.5/fits.sh

<% end -%>
ENV APP_HOME /app

RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY ./bundle /bundle
ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=2 \
  BUNDLE_PATH=/bundle

ADD Gemfile* $APP_HOME/
RUN bundle check || bundle install

COPY . $APP_HOME
