FROM docker:latest

RUN apk update && \
    apk add bash git ruby-json ansible openssh && \
    gem install stack_car --no-ri --no-rdoc && \
<% if options[:rancher] %>
    wget https://github.com/rancher/cli/releases/download/v0.4.1/rancher-linux-amd64-v0.4.1.tar.gz && \
    tar zxfv rancher-linux-amd64-v0.4.1.tar.gz && \
    mv rancher-v0.4.1/rancher /bin/rancher
<% end %>
<% if options[:heroku] %>
    gem install dpl multi_json --no-ri --no-rdoc
<% end %>
