name: Test
on: [ push, pull_request]
jobs: 
  rspec:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Dependencies
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Rspec
      run: 'bundle exec rspec'
